import { createHash } from "node:crypto";
import { z } from "zod";

/**
 * The capability card: what a planner outside the data zone may know about
 * the bound project. Generated by code from the capability catalog the
 * `wren-context-loader` binary emits (`--catalog-out`), never by a model, so
 * what crosses the boundary is exactly what this allow-list names.
 *
 * Allow-list, not deny-list: the zod schemas below strip every key they do
 * not name, so a new catalog or MDL field does not leak by default. Nothing
 * here is computed from data — no sample values, no row counts, no SQL.
 */

const properties = { description: z.string().optional() };
const enumValue = z.object({ value: z.string(), meaning: z.string() });
const column = z.object({ name: z.string(), type: z.string(), ...properties,
  not_null: z.boolean().optional(), is_calculated: z.boolean().optional(), is_hidden: z.boolean().optional(),
  relationship: z.string().optional(), enum_values: z.array(enumValue).default([]) });
const model = z.object({ name: z.string(), ...properties, primary_key: z.array(z.string()).default([]), columns: z.array(column).default([]) });
const relationship = z.object({ name: z.string(), models: z.array(z.string()), join_type: z.string(), condition: z.string() });
const member = z.object({ name: z.string(), type: z.string(), ...properties, granularities: z.array(z.string()).default([]), date_range: z.tuple([z.string(), z.string()]).optional() });
const cube = z.object({ name: z.string(), base_object: z.string(), ...properties,
  measures: z.array(member).default([]), dimensions: z.array(member).default([]), time_dimensions: z.array(member).default([]) });
const view = z.object({ name: z.string(), ...properties });

/** The catalog fields the card may read. Everything else the document carries is dropped here. */
export const capabilityCatalogSchema = z.object({
  catalog_version: z.literal(1),
  project: z.object({ name: z.string().optional(), data_source: z.string().optional() }).default({}),
  models: z.array(model).default([]),
  relationships: z.array(relationship).default([]),
  cubes: z.array(cube).default([]),
  views: z.array(view).default([]),
});
export type CapabilityCatalog = z.infer<typeof capabilityCatalogSchema>;

export interface CapabilityCard {
  readonly text: string;
  readonly bytes: number;
  readonly truncated: boolean;
  /** sha256 hex over `text`; the value a public step's `context` surface fingerprint carries when it received the card. */
  readonly digest: string;
  /** Lines dropped by the size bound, for the trace warning. */
  readonly omittedLines: number;
}

export interface CapabilityCardOptions {
  /** Upper bound on the rendered card in UTF-8 bytes. Default 32 KiB. */
  readonly maxBytes?: number;
}
export const DEFAULT_CARD_MAX_BYTES = 32 * 1024;
const TRUNCATION_MARKER = (omitted: number) => `[card truncated by the size bound: ${omitted} line${omitted === 1 ? "" : "s"} omitted]`;

const ENUM_TAG = /^\s*\[enum\]\s*(.+)$/i;

function describe(text: string | undefined): string {
  return text !== undefined && text.trim().length > 0 ? ` — ${text.trim().replace(/\s+/g, " ")}` : "";
}

/** Enum meanings a description carries as `[enum] A=active, I=inactive` lines (the enrich skill's convention). */
function taggedEnums(description: string | undefined): { value: string; meaning: string }[] {
  if (!description) return [];
  const out: { value: string; meaning: string }[] = [];
  for (const line of description.split(/\r?\n/)) {
    const match = ENUM_TAG.exec(line);
    if (!match) continue;
    for (const pair of match[1]!.split(/[,;]/)) {
      const eq = pair.indexOf("=");
      if (eq > 0) out.push({ value: pair.slice(0, eq).trim(), meaning: pair.slice(eq + 1).trim() });
    }
  }
  return out;
}

/** Renders the card's lines from an already allow-listed catalog. Pure and order-preserving. */
export function renderCapabilityCardLines(catalog: CapabilityCatalog): string[] {
  const lines: string[] = [];
  lines.push("# Capability card");
  lines.push("Schema of the bound project: names, types, descriptions, relationships, cubes, enum meanings and declared time grains. It carries no sample values, row counts or SQL; ask the data oracle for values.");
  const project = [catalog.project.name, catalog.project.data_source ? `(${catalog.project.data_source})` : undefined].filter(Boolean).join(" ");
  if (project) lines.push(`project: ${project}`);
  lines.push("");
  lines.push("## Models");
  if (catalog.models.length === 0) lines.push("- (none)");
  for (const item of catalog.models) {
    const pk = item.primary_key.length ? ` [pk: ${item.primary_key.join(", ")}]` : "";
    lines.push(`- ${item.name}${pk}${describe(item.description)}`);
    for (const col of item.columns) {
      if (col.is_hidden) continue;
      const flags = [col.not_null ? "not null" : undefined, col.is_calculated ? "calculated" : undefined, col.relationship ? `relationship: ${col.relationship}` : undefined].filter(Boolean);
      lines.push(`  - ${col.name}: ${col.type}${flags.length ? ` (${flags.join(", ")})` : ""}${describe(col.description)}`);
    }
  }
  lines.push("");
  lines.push("## Relationships");
  if (catalog.relationships.length === 0) lines.push("- (none)");
  for (const item of catalog.relationships) lines.push(`- ${item.name}: ${item.models.join(" ")} ${item.join_type} on ${item.condition}`);
  lines.push("");
  lines.push("## Cubes");
  if (catalog.cubes.length === 0) lines.push("- (none)");
  for (const item of catalog.cubes) {
    lines.push(`- ${item.name} (base: ${item.base_object})${describe(item.description)}`);
    const render = (label: string, members: typeof item.measures) => {
      if (members.length === 0) return;
      lines.push(`  ${label}: ${members.map((m) => {
        const grains = m.granularities.length ? ` grains: ${m.granularities.join("/")}` : "";
        const range = m.date_range ? ` range: ${m.date_range[0]}..${m.date_range[1]}` : "";
        const extra = grains || range ? ` [${[grains.trim(), range.trim()].filter(Boolean).join("; ")}]` : "";
        return `${m.name} ${m.type}${extra}${describe(m.description)}`;
      }).join("; ")}`);
    };
    render("measures", item.measures);
    render("dimensions", item.dimensions);
    render("time dimensions", item.time_dimensions);
  }
  lines.push("");
  lines.push("## Views");
  if (catalog.views.length === 0) lines.push("- (none)");
  for (const item of catalog.views) lines.push(`- ${item.name}${describe(item.description)}`);
  const enums: string[] = [];
  for (const item of catalog.models) for (const col of item.columns) {
    if (col.is_hidden) continue;
    const values = [...col.enum_values, ...taggedEnums(col.description)];
    if (values.length) enums.push(`- ${item.name}.${col.name}: ${values.map((v) => `${v.value} = ${v.meaning}`).join("; ")}`);
  }
  lines.push("");
  lines.push("## Enum meanings");
  lines.push(...(enums.length ? enums : ["- (none declared)"]));
  return lines;
}

function digestOf(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

/**
 * Builds the card from a raw catalog document. Deterministic: the same
 * catalog yields the same bytes. Size-bounded: when the rendering exceeds
 * `maxBytes`, trailing lines are dropped until it fits and a marker line
 * says how many were omitted; the caller traces that as a warning.
 */
export function buildCapabilityCard(catalog: unknown, options: CapabilityCardOptions = {}): CapabilityCard {
  const parsed = capabilityCatalogSchema.parse(catalog);
  const lines = renderCapabilityCardLines(parsed);
  const maxBytes = options.maxBytes ?? DEFAULT_CARD_MAX_BYTES;
  let kept = lines.length;
  let text = lines.join("\n");
  let omitted = 0;
  while (Buffer.byteLength(text) > maxBytes && kept > 1) {
    kept -= 1;
    omitted = lines.length - kept;
    text = [...lines.slice(0, kept), TRUNCATION_MARKER(omitted)].join("\n");
  }
  return { text, bytes: Buffer.byteLength(text), truncated: omitted > 0, digest: digestOf(text), omittedLines: omitted };
}
